[features]
seeds = false
skip-lint = false
[programs.localnet]
pdas = "CUHtiUABtEJKnCjut9Z7KK2j8nF7WN7QJjhbSrr9DHZB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/rohits/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
